@STATUS_CREATED = 'STATUS_CREATED'
@STATUS_PUBLISHED = 'STATUS_PUBLISHED'
@STATUS_CHANGES_REQUIRED = 'STATUS_CHANGES_REQUIRED'
@STATUS_UPDATED = 'STATUS_UPDATED'
@STATUS_NOT_VISIBLE = 'STATUS_NOT_VISIBLE'

@ITEMS_INCREMENT = 5
