@STATUS_CREATED = 'STATUS_CREATED'
@STATUS_PUBLISHED = 'STATUS_PUBLISHED'
@STATUS_CHANGES_REQUIRED = 'STATUS_CHANGES_REQUIRED'
@STATUS_UPDATED = 'STATUS_UPDATED'
@STATUS_NOT_VISIBLE = 'STATUS_NOT_VISIBLE'
@IMAGE_ROOT = 'https://res.cloudinary.com/ginkgo/image/upload/w_90/'

@ITEMS_INCREMENT = 5
